---
title: "Resume"
---

# Leona Myers

970.778.8471 \| leonamyers18\@gmail.com \| <https://www.linkedin.com/in/leona-myers> \|

### Sustainability Science \| Conservation Biology \| Plant Ecology

An Ecosystem Science & Sustainability major with an interest in the field of conservation biology, while in school I have been involved in sustainability organizations and have worked in in outdoor leadership positions. In professional settings, I bring qualities of detail analysis and interpersonal skills in order to contribute to my ability to work as a motivated team member. I seek to utilize my expertise in organizations focused on ecological conservation and apply my core competencies which include:

-   Lifelong Coloradoan with familiarity with surrounding ecosystems

-   Strong attention to detail with skills in data analysis

-   Empathetic and considerate worker with motivation and passion for ecosystem science

-   Ability to work with a diverse group of people of all ages

## Education

#### Colorado State University, Fort Collins, CO \| Anticipated May 2026 August 2023 – Present

Junior, Ecosystem Science and Sustainability Major, Conservation Biology Minor GPA: 3.6

-   Relevant coursework: Ecology, Physical Geography, Information Management for Sustainability, Biology of Organisms (with lab), Intro to Geospatial Science, Sustainability Science, Sustainable Watersheds, Intro to System Theory of Sustainability, Food, Environment, and Social Justice

#### Rensselaer Polytechnic Institute, Troy, NY August 2022 – May 2023

Freshman, Environmental Engineering

-   Relevant coursework: Chemistry I (with lab), Chemistry II (with lab), Calculus I, Calculus II, Physics I, Environmental Ethics, Intro to Environmental Engineering Analysis

## Work Experience

#### Perennial Sales Associate, Bath Garden Center and Nursery \| Fort Collins, CO \| April 2024 – Present

-   Knowledge of plant species, including care requirements, growth patterns, and common issues.

-   Aided in reaching a sales goal of 100k.

-   Understanding the environmental impact of plant care practices.

#### Campground Assistant, Kebler Corner \| Somerset, CO \| May 2023 – August 2023

-   Guided visitors using geography and navigation skills.

-   Managed data using spreadsheets.

-   Acquired knowledge of the local ecosystem.

#### Nanny, Kebler Corner \| Somerset, CO \| May 2022 – August 2022

-   Effectively communicated with people of all ages.

-   Demonstrated patience and understanding with children.

-   Planned and led outdoor activities, sharing a passion for nature.

#### Barista, BreadWorks \| Paonia, CO \| October 2020 – June 2022

-   Collaborated as a team member, contributing to business success.

-   Interacted with customers and co-workers, showcasing interpersonal skills.

#### Camp Counselor, Wyonegonic \| Denmark, ME \| June 2021 – August 2021

-   Learned about biodiversity and native species.

-   Taught sustainability practices and environmental kindness.

-   Worked with diverse groups of people of various ages and cultural backgrounds.

## Other Relevant Experience

-   National Honor Society Member \| August 2020 -May 2022

-   SUPER (Skills for Undergraduate Participation in Ecological Research) \| August 2024- Present
